REGIONS = [
    {
        "name": "Республика Татарстан (ОЭЗ Алабуга)",
        "lat": 55.75, "lon": 52.06,
        "steel_distance_km": 120,
        "insulation_distance_km": 80,
        "railway_available": True,
        "highway_distance_km": 5,
        "tax_incentives": True,
        "has_reduced_insurance": True,
        "energy_tariff": 4.8,
        "average_salary": 48000,
        "gas_available": True,
        "substation_free_power_kva": 2000,
        "substation_distance_km": 2,
        "connection_cost_rub_per_kw": 8500,
        "urban_env_index": 189,
        "kindergartens_per_100": 62,
        "vocational_colleges": 12,
        "avg_rent_1room": 18000,
        "ecological_iza": 5,
        "cultural_profile": {
            "style": "индустриальный модерн с элементами татарского орнамента",
            "materials": ["бетон", "стекло", "кирпич", "орнаментные панели"],
            "colors": ["терракотовый", "бирюзовый", "золотой"]
        }
    },
    {
        "name": "Калужская область (индустриальные парки)",
        "lat": 54.53, "lon": 36.28,
        "steel_distance_km": 300,
        "insulation_distance_km": 150,
        "railway_available": True,
        "highway_distance_km": 10,
        "tax_incentives": True,
        "has_reduced_insurance": False,
        "energy_tariff": 5.2,
        "average_salary": 42000,
        "gas_available": True,
        "substation_free_power_kva": 1200,
        "substation_distance_km": 1,
        "connection_cost_rub_per_kw": 9500,
        "urban_env_index": 175,
        "kindergartens_per_100": 58,
        "vocational_colleges": 7,
        "avg_rent_1room": 15000,
        "ecological_iza": 4,
        "cultural_profile": {
            "style": "неоклассика с элементами космической тематики",
            "materials": ["стеклофибробетон", "металл", "стекло"],
            "colors": ["белый", "синий", "серый"]
        }
    },
    {
        "name": "Свердловская область (промпарк Богословский)",
        "lat": 56.84, "lon": 60.65,
        "steel_distance_km": 50,
        "insulation_distance_km": 110,
        "railway_available": True,
        "highway_distance_km": 25,
        "tax_incentives": True,
        "has_reduced_insurance": True,
        "energy_tariff": 4.2,
        "average_salary": 45000,
        "gas_available": True,
        "substation_free_power_kva": 1800,
        "substation_distance_km": 3,
        "connection_cost_rub_per_kw": 8000,
        "urban_env_index": 162,
        "kindergartens_per_100": 55,
        "vocational_colleges": 15,
        "avg_rent_1room": 17000,
        "ecological_iza": 6,
        "cultural_profile": {
            "style": "конструктивизм и уральский сказовый стиль",
            "materials": ["камень", "дерево", "кортеновская сталь"],
            "colors": ["зелёный", "коричневый", "ржавый"]
        }
    },
    {
        "name": "Ростовская область (Азовский индустриальный парк)",
        "lat": 47.24, "lon": 39.71,
        "steel_distance_km": 400,
        "insulation_distance_km": 280,
        "railway_available": False,
        "highway_distance_km": 18,
        "tax_incentives": False,
        "has_reduced_insurance": False,
        "energy_tariff": 6.0,
        "average_salary": 35000,
        "gas_available": False,
        "substation_free_power_kva": 800,
        "substation_distance_km": 5,
        "connection_cost_rub_per_kw": 12000,
        "urban_env_index": 155,
        "kindergartens_per_100": 50,
        "vocational_colleges": 9,
        "avg_rent_1room": 14000,
        "ecological_iza": 7,
        "cultural_profile": {
            "style": "южнорусская эклектика с казачьими мотивами",
            "materials": ["белый кирпич", "керамика", "металл"],
            "colors": ["белый", "красный", "золотой"]
        }
    },
    {
        "name": "Ленинградская область (промзона Горелово)",
        "lat": 59.74, "lon": 30.34,
        "steel_distance_km": 250,
        "insulation_distance_km": 90,
        "railway_available": True,
        "highway_distance_km": 8,
        "tax_incentives": False,
        "has_reduced_insurance": False,
        "energy_tariff": 5.8,
        "average_salary": 55000,
        "gas_available": True,
        "substation_free_power_kva": 2500,
        "substation_distance_km": 0.5,
        "connection_cost_rub_per_kw": 15000,
        "urban_env_index": 195,
        "kindergartens_per_100": 68,
        "vocational_colleges": 14,
        "avg_rent_1room": 28000,
        "ecological_iza": 3,
        "cultural_profile": {
            "style": "северный модерн и скандинавский минимализм",
            "materials": ["гранит", "дерево", "стекло"],
            "colors": ["серый", "белый", "пастельные"]
        }
    }
]